const sentences = [
  "I didn't know what to wear to my best friend's funeral.",
  "There used to be a big cherry tree behind my house.",
  "Sometimes, books and movies made her feel things she couldn't explain.",
  "My bandaid wasn't sticky anymore so it fell off on the way to school.",
  "He only had one drink but he's completely wasted.",
  "In Hong Kong, everyone lives stacked together.",
  "Her parents had been separated for almost three years, but she never expected them to actually go through with the divorce.",
  "These are the things that I want from a relationship.",
  "When one considers the issue from a different perspective, the answer seems to change.",
  "She twisted her ankle and couldn't go to soccer anymore.",
  "You can always find baked goods somewhere in my pantry.",
  "The alligator's teeth were so scary that I ran back to the car as fast as I could.",
  "They sold shampoo and conditioner, but no plain soap.",
  "She got a discount to buy the stickers online.",
  "Once you master cooking, you’ll start tweaking popular recipes, and that’s when it becomes even more fun.",
  "Checking things off the list is the best feeling.",
  "Let's all just take a moment to breathe, please.",
  "She decided to take the bus because it was supposed to be quicker, but then it ended up being twenty minutes late.",
  "She fell off the bull two seconds after she got on.",
  "Rosa crossed Mary's name off the list.",
  "She couldn't find the basket she was looking for.",
  "What he likes best is being around his friends.",
  "I found a gold coin on the playground after school today.",
  "She sells Christmas trees.",
  "Going to a bar is a fun thing to do.",
  "She got hiccups and couldn't get rid of them for three hours.",
  "Many big projects will be completed in the 21st century.",
  "They will be here shortly.",
  "The caffeine was making her jittery.",
  "If you go there, you will find him.",
  "It’s time to watch TV.",
  "They are still edible.",
  "I didn’t want to take a side in the argument.",
  "Captain America is my favorite Avenger.",
  "Get your act together.",
  "Over time, she realized she would never know how to cook.",
  "You'll move more than before.",
  "He was president from 2008 to 2016.",
  "The window looks out on a garden.",
  "The girl wore her hair in two braids, tied with two blue bows.",
  "Looking back, I know it was the right decision.",
  "It is going to happen on Friday.",
  "You must be happy.",
  "I need to clean my room.",
  "I want the stability of a full-time job, but I'm not interested in the rigidity of working nine to five.",
  "You have a big house.",
  "She wanted to be a professor when she was in high school, but then she realized how few academic jobs there are on the market.",
  "She had a big scar on her knee from falling off her bike as a kid.",
  "They may come in handy one day.",
  "A wet road is usually slippery.",
  "She wanted to get gastric bypass surgery, but her insurance wouldn't cover it.",
  "Imagine I am deciding if I like some new, heretofore untasted food.",
  "He earned his PhD in physics at the age of 89.",
  "In Australia, there is a store called PieFace which sells meat pies with smiley faces on them.",
  "Don't go there.",
  "They make wonderful walking buddies.",
  "The church was white and brown and looked very old.",
  "Watch out, there's quicksand.",
  "She likes to play soccer.",
  "I will open the door.",
  "I will have a baby in the near future.",
  "That was the president on the phone.",
  "Well, that's a big surprise.",
  "Every year Americans pay half a trillion in rent.",
  "You have a beautiful home.",
  "I started drinking when I was sixteen, but I'm European.",
  "I wish I had never gone surfing that day.",
  "The professor marked down one point for every use of the word 'interesting' in a paper.",
  "I won’t believe it unless I see it with my own eyes.",
  "She always worried that things would embarrass themselves, because if she was in front of a crowd she would always be worried about embarrassing herself.",
  "I don't want to drink alcohol.",
  "It was so cold that no one wanted to go outside.",
  "The wind was so strong it swept her hat right away.",
  "I don't think I liked the movie.",
  "It's been three months and his stab wound hasn't healed yet.",
  "The fan is blowing in my face right now.",
  "The footballers were very upset when they cancelled the game because of lightning threats.",
  "Elizabeth is traveling all around the country to hear directly from people like you.",
  "I'm always on time.",
  "The contents of the box are listed on the label.",
  "My pen broke and leaked blue ink all over my new dress.",
  "Historical sites are awesome to walk through.",
  "I love bacon, eggs, and orange juice for breakfast.",
  "Big Brother is watching.",
  "Pluto may not be a planet anymore, but it's a planet in my heart.",
  "My biggest problem is deciding what to do next.",
  "You never get serious.",
  "Is this a joke?",
  "We will get awards.",
  "Threat is coming.",
  "None is going to save you.",
  "John Marshall is a friend of mine.",
  "This will be remembered forever.",
  "Bunch of heartless people."
];

export default sentences;

// CommonJS alternative:
// module.exports = sentences;
